// v0.10.0: brief compiler.
//
// Pure function: ConversationBuffer + ProposePlanIntent -> Brief.
// Deterministic given the same input. The compiler does NOT call the LLM;
// the conversation agent has already produced a draft via propose_plan and
// the compiler's job is to assemble a real Brief shape from it + the
// conversation context.
//
// LOAD-BEARING INVARIANT: conservative authorized_costs.
//
//   The compiler NEVER auto-grants destructive categories. Even when the
//   agent's intended_actions list says "make git commits" or "publish to
//   remote" or "send messages", the compiler routes those through the
//   Phase 3 destructive gate at execution time instead of pre-authorizing
//   them in the brief. The user sees them as natural-language confirms
//   ("publish this change to your repo?") during execution, not as silent
//   grants in a plan they might skim past.
//
//   If anyone expands this auto-grant list, it's a P0 regression. Tests
//   in tests/chat/compile.test.ts pin the conservative set adversarially.

import type { Brief, BriefFrontmatter, BriefSections, ExecutionMode } from "../types.js";
import type { AuthCategory } from "../auth/categories.js";
import type { ProposePlanIntent, IntendedAction } from "./intent.js";

// The destructive categories the compiler refuses to auto-grant. These fire
// through the Phase 3 gate during execution regardless of what the agent
// claims it intends to do.
//
// Adding a category here LOOSENS the gate. Don't, without a CHANGELOG note
// and an updated adversarial fixture in tests/chat/compile.test.ts.
export const DESTRUCTIVE_NEVER_AUTOGRANT: ReadonlySet<string> = new Set([
  "filesystem_delete",
  "shell_exec",
  "http_fetch",
  "paid_api_call",
  "git_write",
  "git_push",
  "deploy",
  "external_message",
]);

// Static categories the compiler will grant when the agent declares the intent
// AND the user approves the plan. These are non-destructive enough that the
// chat plan-presentation step + explicit user approval is the right gate.
//
// filesystem_read is always granted (default-allowed in the runtime anyway).
// filesystem_write is the most common chat workflow ("edit a page", "draft
// a doc") and is bounded by the workdir sandbox; we surface it explicitly in
// the plan and grant on approval. Anything destructive past write goes
// through Phase 3.
export const SAFE_AUTOGRANT: ReadonlySet<string> = new Set([
  "filesystem_read",
  "filesystem_write",
]);

// ---------------------------------------------------------------------------
// Conversation buffer. The compiler reads this to derive project slug and
// (optionally) deadline / notes. Same shape as the chat-store's persisted
// turn events, minus internal fields.

export interface ConversationTurn {
  role: "user" | "agent";
  content: string;
  at: string;
}

export interface ConversationBuffer {
  turns: ConversationTurn[];
}

// ---------------------------------------------------------------------------
// Compile options. The session manager provides project slug + working dir.

export interface CompileOptions {
  // Operator-supplied project slug (via --project flag or working-dir
  // inference). Compiler does not LLM-derive it.
  projectSlug: string;
  // Brief id to stamp. Compiler accepts a precomputed id so the chat session
  // manager can correlate it with the execution_started event.
  briefId: string;
  // Workdir for the run. Compiler stamps it into the brief frontmatter.
  workdir: string;
  // Source chat id for the `# Generated by openwar chat` provenance header.
  // Optional; tests can omit.
  chatId?: string;
  // The mode the compiled brief should run in. Default "gated" (chat sessions
  // never auto-execute past phase 3 without explicit user approval).
  mode?: ExecutionMode;
}

// ---------------------------------------------------------------------------
// Compile result.

export interface CompileSuccess {
  ok: true;
  brief: Brief;
  // Categories the agent's intended_actions WANTED but the compiler refused
  // to auto-grant. Surfaced in the plan's "Not authorized" section.
  refused_categories: string[];
  // Plain-English explanations to thread into the plan presenter.
  explanations: string[];
}

export interface CompileFailure {
  ok: false;
  missing: MissingField[];
  // Phrased for the user, not the agent. The session manager surfaces these
  // as a clarification turn before the plan.
  questions: string[];
}

export interface MissingField {
  field: string;
  severity: "required" | "recommended";
}

export type CompileResult = CompileSuccess | CompileFailure;

// ---------------------------------------------------------------------------
// The compiler itself.

export function compileBriefFromChat(
  buffer: ConversationBuffer,
  proposal: ProposePlanIntent,
  options: CompileOptions,
): CompileResult {
  const missing: MissingField[] = [];
  const questions: string[] = [];

  // Required: deliverables. Agent must have populated these via propose_plan.
  if (!proposal.draft_brief.deliverables || proposal.draft_brief.deliverables.length === 0) {
    missing.push({ field: "deliverables", severity: "required" });
    questions.push("What specifically do you want me to produce? A list of one to three deliverables would help.");
  }

  // Required: project slug. The session manager provides it; the compiler
  // does NOT derive it from the conversation.
  if (!options.projectSlug || options.projectSlug.trim().length === 0) {
    missing.push({ field: "project", severity: "required" });
    questions.push("Which project should this run under? You can pass --project <slug> when starting the chat.");
  }

  // Required: brief id. The session manager supplies a generated one; if
  // not, the compiler reports it so callers don't end up with collisions.
  if (!options.briefId || options.briefId.trim().length === 0) {
    missing.push({ field: "brief_id", severity: "required" });
    questions.push("Internal: brief id missing. This is a bug; please report.");
  }

  if (missing.length > 0) {
    return { ok: false, missing, questions };
  }

  // Conservative authorized_costs: filter the agent's intended_actions
  // through SAFE_AUTOGRANT. Destructive intents are kept as a separate list
  // (refused_categories) for the plan-presenter to surface in "Not authorized".
  const granted = new Set<AuthCategory>();
  const refused = new Set<string>();
  const explanations: string[] = [];
  for (const action of proposal.draft_brief.intended_actions) {
    const cat = action.category.trim();
    if (cat.length === 0) continue;
    if (SAFE_AUTOGRANT.has(cat)) {
      granted.add(cat as AuthCategory);
      continue;
    }
    if (DESTRUCTIVE_NEVER_AUTOGRANT.has(cat)) {
      refused.add(cat);
      continue;
    }
    // Unknown category. Treat as destructive (safe default). Surfaces in
    // the plan as "I'll ask before doing X."
    refused.add(cat);
    explanations.push(
      `Unknown category "${cat}" (action: ${action.description}). Treating as destructive; will ask before running.`,
    );
  }
  // filesystem_read is the runtime default-allowed category. We always
  // include it explicitly so the brief frontmatter is unambiguous.
  granted.add("filesystem_read");

  // Sections: deliverables become a bulleted list; constraints / out-of-scope
  // mirror the draft. Objective is the first deliverable phrased as a goal.
  const deliverablesText = proposal.draft_brief.deliverables
    .map((d) => `- ${d}`)
    .join("\n");
  const constraintsText = (proposal.draft_brief.constraints ?? []).map((c) => `- ${c}`).join("\n");
  const outOfScopeText = (proposal.draft_brief.out_of_scope ?? []).map((c) => `- ${c}`).join("\n");
  const toolsText = describeIntendedActions(proposal.draft_brief.intended_actions);
  const notes = renderNotes(buffer, options, refused);

  const sections: BriefSections = {
    objective: proposal.draft_brief.deliverables[0]!,
    deliverables: deliverablesText,
    constraints: constraintsText.length > 0 ? constraintsText : "(none specified)",
    tools_required: toolsText,
    notes,
    extra: {},
  };

  const frontmatter: BriefFrontmatter = {
    project: options.projectSlug,
    brief_id: options.briefId,
    scope_locked: true,
    mode: options.mode ?? "gated",
    authorized_costs: [...granted].sort(),
    workdir: options.workdir,
  };

  const raw = renderRawBriefMarkdown(frontmatter, sections, buffer, options);

  return {
    ok: true,
    brief: { frontmatter, sections, raw },
    refused_categories: [...refused].sort(),
    explanations,
  };
}

// ---------------------------------------------------------------------------
// Helpers.

function describeIntendedActions(actions: readonly IntendedAction[]): string {
  if (actions.length === 0) return "(text only)";
  return actions.map((a) => `- ${a.description} (${a.category})`).join("\n");
}

function renderNotes(buffer: ConversationBuffer, options: CompileOptions, refused: Set<string>): string {
  const parts: string[] = [];
  if (options.chatId) parts.push(`Generated by openwar chat (session: ${options.chatId}).`);
  parts.push("Replay semantics: this brief replays the deliverables on the named project. If repo state has drifted since the chat ran, the agent may need different actions.");
  if (refused.size > 0) {
    parts.push(`Destructive actions surfaced via Phase 3 prompts during execution: ${[...refused].sort().join(", ")}.`);
  }
  const userTurns = buffer.turns.filter((t) => t.role === "user").length;
  parts.push(`Source: ${userTurns} user turn(s) across the chat session.`);
  return parts.join("\n\n");
}

// Serialize the brief back to YAML-frontmatter markdown so the chat layer can
// preserve the brief file format AND optionally save it as a reusable brief.
// The runtime's `parseBrief` accepts either a path or a raw string; this
// raw string is what the runtime sees.
export function renderRawBriefMarkdown(
  fm: BriefFrontmatter,
  sections: BriefSections,
  buffer: ConversationBuffer,
  options: CompileOptions,
): string {
  const fmLines: string[] = ["---"];
  fmLines.push(`project: ${fm.project}`);
  if (fm.brief_id) fmLines.push(`brief_id: ${fm.brief_id}`);
  fmLines.push(`scope_locked: ${fm.scope_locked}`);
  if (fm.mode) fmLines.push(`mode: ${fm.mode}`);
  fmLines.push(`authorized_costs:`);
  for (const c of fm.authorized_costs) fmLines.push(`  - ${c}`);
  if (fm.workdir) fmLines.push(`workdir: ${fm.workdir}`);
  fmLines.push("---");

  const bodyLines: string[] = [];
  if (options.chatId) bodyLines.push(`# Generated by openwar chat (session: ${options.chatId})`);
  bodyLines.push("");
  bodyLines.push("# Objective");
  bodyLines.push("");
  bodyLines.push(sections.objective);
  bodyLines.push("");
  bodyLines.push("# Deliverables");
  bodyLines.push("");
  bodyLines.push(sections.deliverables);
  bodyLines.push("");
  bodyLines.push("# Constraints");
  bodyLines.push("");
  bodyLines.push(sections.constraints);
  bodyLines.push("");
  bodyLines.push("# Tools required");
  bodyLines.push("");
  bodyLines.push(sections.tools_required);
  bodyLines.push("");
  bodyLines.push("# Notes / unknowns");
  bodyLines.push("");
  bodyLines.push(sections.notes);
  bodyLines.push("");

  // Saved-brief artifact includes the source conversation as a markdown
  // quoted block so anyone reading the brief later understands its origin.
  // Section header is conservative so `parseBrief` ignores it as "extra".
  if (buffer.turns.length > 0) {
    bodyLines.push("# Source conversation");
    bodyLines.push("");
    for (const turn of buffer.turns) {
      bodyLines.push(`> **${turn.role}** (${turn.at}):`);
      for (const line of turn.content.split("\n")) {
        bodyLines.push(`> ${line}`);
      }
      bodyLines.push(">");
    }
  }

  return fmLines.join("\n") + "\n" + bodyLines.join("\n") + "\n";
}
