// v0.10.0: save-as-brief flow.
//
// At the end of a successful execution, the chat session can persist the
// compiled brief to ~/.openwar/briefs/<name>.md. The saved file is a full
// v0.x-compatible YAML-frontmatter markdown file (the same shape `openwar
// run` already consumes) plus a Source-conversation block as a markdown
// blockquote.
//
// The renderRawBriefMarkdown helper from src/chat/compile.ts already
// produces the wire format; this module is the I/O wrapper.

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname } from "node:path";
import { savedBriefPath, briefsDir } from "../state/paths.js";
import { slugify } from "./commands.js";
import type { Brief } from "../types.js";
import { renderRawBriefMarkdown, type ConversationBuffer } from "./compile.js";

export interface SaveBriefOptions {
  // Operator-supplied name; if absent, derived from the first deliverable.
  name?: string;
  // The compiled brief. We re-render with `buffer` so the saved artifact
  // includes the Source-conversation block even if the in-memory `brief.raw`
  // didn't (the runtime's compile output already includes it, but this lets
  // tests pass an empty raw string and rely on the renderer here).
  brief: Brief;
  // Conversation buffer to include as Source-conversation. Empty array if
  // the operator wants to save without conversation context.
  buffer: ConversationBuffer;
  // Source chat id, surfaced in the # Generated by openwar chat header.
  chatId: string;
  // When true, refuse to overwrite an existing file. Default true.
  noOverwrite?: boolean;
}

export interface SaveBriefResult {
  path: string;
  name: string;
  wroteNew: boolean;
}

export class SaveBriefError extends Error {
  readonly code: "EXISTS" | "WRITE_FAILED";
  readonly path: string;
  constructor(code: "EXISTS" | "WRITE_FAILED", path: string, message: string) {
    super(message);
    this.code = code;
    this.path = path;
    this.name = "SaveBriefError";
  }
}

export function saveBriefFile(opts: SaveBriefOptions): SaveBriefResult {
  // Resolve the name. Operator-supplied wins; otherwise slugified first
  // deliverable; otherwise chat-brief.
  const proposed = opts.name && opts.name.trim().length > 0
    ? slugify(opts.name)
    : slugify(opts.brief.sections.objective ?? "chat-brief");
  const path = savedBriefPath(proposed);
  const noOverwrite = opts.noOverwrite !== false;
  if (noOverwrite && existsSync(path)) {
    throw new SaveBriefError(
      "EXISTS",
      path,
      `A saved brief already exists at ${path}. Choose a different name with /save <name>, or rerun /save and the chat will suggest a unique one.`,
    );
  }
  try {
    mkdirSync(dirname(path), { recursive: true });
    const raw = renderRawBriefMarkdown(
      opts.brief.frontmatter,
      opts.brief.sections,
      opts.buffer,
      {
        projectSlug: opts.brief.frontmatter.project,
        briefId: opts.brief.frontmatter.brief_id ?? "",
        workdir: opts.brief.frontmatter.workdir ?? "",
        chatId: opts.chatId,
      },
    );
    writeFileSync(path, raw, "utf8");
    return { path, name: proposed, wroteNew: true };
  } catch (err) {
    throw new SaveBriefError(
      "WRITE_FAILED",
      path,
      `Could not write saved brief to ${path}: ${(err as Error).message}`,
    );
  }
}

// Suggest a unique name when the operator's pick collides. Appends a -N
// suffix and bumps until the path is free. Capped at 1000 attempts so
// runaway filesystems don't hang the chat session.
export function suggestUniqueName(baseName: string): string {
  const base = slugify(baseName);
  if (!existsSync(savedBriefPath(base))) return base;
  for (let i = 2; i < 1000; i++) {
    const candidate = `${base}-${i}`;
    if (!existsSync(savedBriefPath(candidate))) return candidate;
  }
  // Pathological fallback.
  return `${base}-${Date.now().toString(36)}`;
}

export { briefsDir };
