// v0.10.0 save-brief: round-trip (write to disk, re-parse via parseBrief).

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const TMP = mkdtempSync(join(tmpdir(), "openwar-v10-savebrief-"));
process.env.OPENWAR_HOME = TMP;

const { saveBriefFile, suggestUniqueName, SaveBriefError } = await import("../../src/chat/save-brief.js");
const { compileBriefFromChat } = await import("../../src/chat/compile.js");
const { savedBriefPath, briefsDir } = await import("../../src/state/paths.js");
const { parseBrief } = await import("../../src/brief.js");
type ConversationBuffer = import("../../src/chat/compile.js").ConversationBuffer;
type ProposePlanIntent = import("../../src/chat/intent.js").ProposePlanIntent;

test.after(() => {
  rmSync(TMP, { recursive: true, force: true });
  delete process.env.OPENWAR_HOME;
});

function compile() {
  const proposal: ProposePlanIntent = {
    intent: "propose_plan",
    plan_text: "Read and add testimonials.",
    draft_brief: {
      deliverables: ["testimonials section"],
      intended_actions: [
        { description: "read files", category: "filesystem_read" },
        { description: "write files", category: "filesystem_write" },
      ],
    },
  };
  const buffer: ConversationBuffer = {
    turns: [
      { role: "user", at: "t1", content: "add testimonials" },
      { role: "agent", at: "t2", content: "got it", intent: undefined as never },
    ],
  };
  const r = compileBriefFromChat(buffer, proposal, {
    projectSlug: "demo",
    briefId: "2026-05-18-save-x",
    workdir: "/work",
    chatId: "chat-abc-1234",
  });
  if (!r.ok) throw new Error("compile failed");
  return { brief: r.brief, buffer };
}

test("saveBriefFile: writes a runnable YAML-frontmatter markdown file", () => {
  const { brief, buffer } = compile();
  const result = saveBriefFile({ name: "round-trip", brief, buffer, chatId: "chat-abc-1234" });
  assert.equal(result.wroteNew, true);
  assert.match(result.path, /briefs[\\/]round-trip\.md$/);
  assert.ok(existsSync(result.path));
  const raw = readFileSync(result.path, "utf8");
  // Has frontmatter.
  assert.match(raw, /^---\n/);
  assert.match(raw, /\nproject: demo\n/);
  // Has the chat-provenance header.
  assert.match(raw, /# Generated by openwar chat \(session: chat-abc-1234\)/);
  // Round-trips through the runtime's brief parser.
  const reparsed = parseBrief(raw);
  assert.equal(reparsed.frontmatter.project, "demo");
  assert.equal(reparsed.frontmatter.mode, "gated");
  assert.deepEqual(reparsed.frontmatter.authorized_costs, ["filesystem_read", "filesystem_write"]);
});

test("saveBriefFile: name defaulted from first deliverable when not provided", () => {
  const { brief, buffer } = compile();
  const result = saveBriefFile({ brief, buffer, chatId: "chat-abc-1234" });
  assert.match(result.name, /testimonials/);
});

test("saveBriefFile: refuses to overwrite by default (noOverwrite=true)", () => {
  const { brief, buffer } = compile();
  saveBriefFile({ name: "exists-already", brief, buffer, chatId: "x" });
  assert.throws(
    () => saveBriefFile({ name: "exists-already", brief, buffer, chatId: "y" }),
    (err: unknown) => err instanceof SaveBriefError && (err as InstanceType<typeof SaveBriefError>).code === "EXISTS",
  );
});

test("suggestUniqueName: appends -N suffix when base collides", () => {
  // Make sure a collision exists.
  const { brief, buffer } = compile();
  saveBriefFile({ name: "collision", brief, buffer, chatId: "x" });
  const next = suggestUniqueName("collision");
  // Expect either "collision-2" if no -2 exists yet, or higher.
  assert.match(next, /^collision-\d+$/);
  assert.notEqual(next, "collision");
});

test("suggestUniqueName: free name returns the slug unchanged", () => {
  const free = suggestUniqueName("never-saved-this");
  assert.equal(free, "never-saved-this");
});

test("savedBriefPath sits under briefsDir()", () => {
  const path = savedBriefPath("anything");
  assert.ok(path.startsWith(briefsDir()));
  assert.match(path, /\.md$/);
});
